[package]
name = "ausgarde-server"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["libs/*"]

[dependencies]
ausgarde = { path = "libs/ausgarde" }
actix-web = "4.9.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
serde_json = "1.0.133"